name: Build Docker image CS2 VPK Decompiler - Github Version

on:
  schedule:
    - cron: '0 5 * * 1'
  push:
    branches: [ "master" ]
    # Publish semver tags as releases.
    paths:
      - '.github/workflows/docker-build-cs2vpkdecompiler-github.yml'
      - 'CS2VPKDecompiler-Github/**'
  pull_request:
    branches: [ "master" ]
    paths:
      - '.github/workflows/docker-build-cs2vpkdecompiler-github.yml'
      - 'CS2VPKDecompiler-Github/**'

concurrency:
  group: ${{ github.workflow }}

env:
  TITLE: CS2 VPK Decompiler Github
  # github.repository as <account>/<repo>
  GHCR_SLUG: ghcr.io/lifeismana/cs2-vpk-decompiler-github

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.GHCR_SLUG }}
          labels: |
            maintainer=${{ github.repository_owner }}
            org.opencontainers.image.vendor=${{ github.repository_owner }}
            org.opencontainers.image.title=${{ env.TITLE }}

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3.10.0

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v6.17.0
        with:
          context: "{{defaultContext}}:CS2VPKDecompiler-Github"
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.GHCR_SLUG }}:latest
          cache-from: ${{ env.GHCR_SLUG }}:latest
          labels: ${{ steps.meta.outputs.labels }}
